version: "3.9"

services:
  api:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server/output:/app/output
    environment:
      - PYTHONPATH=/app
  web:
    build:
      context: ./client
    depends_on:
      - api
    ports:
      - "4173:80"
